- hosts: poc_group
  gather_facts: no

  tasks:
    - name: show command test
      ios_command:
        commands:
          - show version
          - show clock
      register: result

    - name: debug output
      debug:
        msg: "{{ result.stdout_lines[0] }}"
